const gelist = [
  {
    college: 'L&S ',
    codes: [
      'A1 ',
      'A2 ',
      'B  ',
      'C  ',
      'D  ',
      'E  ',
      'F  ',
      'G  ',
      'ETH',
      'EUR',
      'NWC',
      'QNT',
      'WRT'
    ]
  }, {
    college: 'ENGR',
    codes: [
      'A1 ',
      'A2 ',
      'D  ',
      'E  ',
      'F  ',
      'G  ',
      'H  ',
      'E1 ',
      'ETH',
      'EUR',
      'NWC',
      'WRT'
    ]
  }, {
    college: 'CRST',
    codes: [
      'A2 ',
      'B  ',
      'C  ',
      'D  ',
      'E  ',
      'F  ',
      'G  ',
      'ETH',
      'EUR',
      'NWC',
      'QNT',
      'WRT'
    ]
  }, {
    college: 'UCSB',
    codes: [
      'AMH',
      'SUB'
    ]
  }
]

const deptlist = [
  { code: 'ANTH ', name: 'Anthropology' },
  { code: 'ART  ', name: 'Art' },
  { code: 'ARTHI', name: 'Art History' },
  { code: 'ARTST', name: 'Art Studio' },
  { code: 'AS AM', name: 'Asian American Studies' },
  { code: 'ASTRO', name: 'Astronomy' },
  { code: 'BIOL ', name: 'Biology (Creative Studies)' },
  { code: 'BMSE ', name: 'Biomolecular Science and Engineering' },
  { code: 'BL ST', name: 'Black Studies' },
  { code: 'CH E ', name: 'Chemical Engineering' },
  { code: 'CHEM ', name: 'Chemistry and Biochemistry' },
  { code: 'CH ST', name: 'Chicano Studies' },
  { code: 'CHIN ', name: 'Chinese' },
  { code: 'CLASS', name: 'Classics' },
  { code: 'COMM ', name: 'Communication' },
  { code: 'C LIT', name: 'Comparative Literature' },
  { code: 'CMPSC', name: 'Computer Science' },
  { code: 'CMPTG', name: 'Computing (Creative Studies)' },
  { code: 'CNCSP', name: 'Counseling, Clinical, School Psychology' },
  { code: 'DANCE', name: 'Dance' },
  { code: 'DYNS ', name: 'Dynamical Neuroscience' },
  { code: 'EARTH', name: 'Earth Science' },
  { code: 'EACS ', name: 'East Asian Cultural Studies' },
  { code: 'EEMB ', name: 'Ecology, Evolution &amp; Marine Biology' },
  { code: 'ECON ', name: 'Economics' },
  { code: 'ED   ', name: 'Education' },
  { code: 'ECE  ', name: 'Electrical Computer Engineering' },
  { code: 'ENGR ', name: 'Engineering Sciences' },
  { code: 'ENGL ', name: 'English' },
  { code: 'EDS  ', name: 'Environmental Data Science' },
  { code: 'ESM  ', name: 'Environmental Science &amp; Management' },
  { code: 'ENV S', name: 'Environmental Studies' },
  { code: 'ESS  ', name: 'Exercise &amp; Sport Studies' },
  { code: 'ES   ', name: 'Exercise Sport' },
  { code: 'FEMST', name: 'Feminist Studies' },
  { code: 'FAMST', name: 'Film and Media Studies' },
  { code: 'FR   ', name: 'French' },
  { code: 'GEN S', name: 'General Studies (Creative Studies)' },
  { code: 'GEOG ', name: 'Geography' },
  { code: 'GER  ', name: 'German' },
  { code: 'GPS  ', name: 'Global Peace and Security' },
  { code: 'GLOBL', name: 'Global Studies' },
  { code: 'GRAD ', name: 'Graduate Division' },
  { code: 'GREEK', name: 'Greek' },
  { code: 'HEB  ', name: 'Hebrew' },
  { code: 'HIST ', name: 'History' },
  { code: 'INT  ', name: 'Interdisciplinary' },
  { code: 'ITAL ', name: 'Italian' },
  { code: 'JAPAN', name: 'Japanese' },
  { code: 'KOR  ', name: 'Korean' },
  { code: 'LATIN', name: 'Latin' },
  { code: 'LAIS ', name: 'Latin American and Iberian Studies' },
  { code: 'LING ', name: 'Linguistics' },
  { code: 'LIT  ', name: 'Literature (Creative Studies)' },
  { code: 'MARSC', name: 'Marine Science' },
  { code: 'MATRL', name: 'Materials' },
  { code: 'MATH ', name: 'Mathematics' },
  { code: 'ME   ', name: 'Mechanical Engineering' },
  { code: 'MAT  ', name: 'Media Arts and Technology' },
  { code: 'ME ST', name: 'Medieval Studies' },
  { code: 'MES  ', name: 'Middle East Studies' },
  { code: 'MS   ', name: 'Military Science' },
  { code: 'MCDB ', name: 'Molecular, Cellular &amp; Develop. Biology' },
  { code: 'MUS  ', name: 'Music' },
  { code: 'MUS A', name: 'Music Performance Laboratories' },
  { code: 'PHIL ', name: 'Philosophy' },
  { code: 'PHYS ', name: 'Physics' },
  { code: 'POL S', name: 'Political Science' },
  { code: 'PORT ', name: 'Portuguese' },
  { code: 'PSY  ', name: 'Psychology' },
  { code: 'RG ST', name: 'Religious Studies' },
  { code: 'RENST', name: 'Renaissance Studies' },
  { code: 'RUSS ', name: 'Russian' },
  { code: 'SLAV ', name: 'Slavic' },
  { code: 'SOC  ', name: 'Sociology' },
  { code: 'SPAN ', name: 'Spanish' },
  { code: 'SHS  ', name: 'Speech &amp; Hearing Sciences' },
  { code: 'PSTAT', name: 'Statistics &amp; Applied Probability' },
  { code: 'TMP  ', name: 'Technology Management' },
  { code: 'THTR ', name: 'Theater' },
  { code: 'WRIT ', name: 'Writing' },
  { code: 'W&L  ', name: 'Writing &amp; Literature (Creative Studies)' }
]

export default {
  ge: gelist,
  dept: deptlist
}
